name: MobileMoney Build and Deployment Workflow
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: Install Node Modules
        run: npm install

      - name: Run the Build
        run: npm run build 
      
      - name: Upload the Test Coverage Results
        uses: actions/upload-artifact@v2
        with:
          name: build-files
          path: build
        if: always()       


  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install -g surge
   
      - name: Download the Build Folder from Previous Stage
        uses: actions/download-artifact@v2
        with:
          name: build-files

      - name: Debugging Verify the Path
        run: ls -R

      - name: Push the files to Surge Server
        run: surge ./ vkplanbtesting-1234.surge.sh --token ${{ secrets.SURGE_TOKEN }}
